### PR TITLE
Reap failed agent

### PR DESCRIPTION
**Pull request by gabriel-samfira**
This change reaps runners that appear as `offline` in github and have their `RUNNER STATUS` set to `failed`. Runners that are in this state have registered themselves in GutHub, but failed at a later stage in the setup process. We reap them if no new updates have been made to the instance after the configured pool timeout.

This change also adds a retry when running `config.sh` via userdata. Hopefully in future releases we can switch to using [jit runners](https://github.blog/changelog/2023-06-02-github-actions-just-in-time-self-hosted-runners/) but for the time being, this is not available for GHE.

Fixes: https://github.com/cloudbase/garm/issues/104

### CODE REVIEW

**Comment by gabriel-samfira** [comment]
I'm going to go ahead and merge this. @SystemKeeper if the problem persists after using this patch, feel free to re-open the issue.

**Comment by SystemKeeper** [comment]
Thanks @gabriel-samfira! I’ll try to install it as soon as possible :)

**Comment by gabriel-samfira** [comment]
No rush! This needed to be done anyway. It should resolve your issue on two fronts:

  * configure is retried 5 times before we give up
  * failed agent is reaped when the pool bootstrap timeout is reached (this is configurable per pool via `garm-cli pool update --runner-bootstrap-timeout`)

So either way, you should see no more runners linger.

**Comment by gabriel-samfira** [comment]
Apropos, this also added a ```make build``` target which just builds the binaries using `go build` and sets the proper version. This is set as a default, so you can just run `make`. The `build-static` target is still there in case you need it.

**Comment by SystemKeeper** [comment]
Quick feedback after this PR: no issues to report 🙂

**Pull request merged**
